### ISSUE TITLE
OMR builds not passed --disable-warnings-as-errors when configuring

### ISSUE THREAD

**Issue by rwy0717** [ibmruntimes/openj9-openjdk-jdk9#10]
This project's top level configure script has an option to enable/disable warnings as errors.

When we disable warnings as errors, this should affect the OMR and openj9 subprojects. Currently, OMR always builds with warnings as errors enabled, regardless of this option.

**Comment by andrew-m-leonard** [comment]
This will be an issue with OMR and it's makefiles, needs raising in Eclipse/openj9-omr.

**Comment by rwy0717** [comment]
I don't think this is an issue with OMR. OMR Has a way to disable warnings as errors that works. The problem is that disabling warnings as errors in this metaproject doesn't filter down to openj9 or omr.

**Comment by mstoodle** [comment]
@rwy0717 Maybe a better title then? Something like "OMR builds not passed --disable-warnings-as-errors when configuring" ?

**Comment by rwy0717** [comment]
Good point, done. I'll try to make the description a little clearer too.

**Comment by keithc-ca** [comment]
Silly question: Why would we need to _disable_ warnings as errors in OMR when compiles normally succeed with warnings as errors _enabled_? Is someone contemplating introducing code somewhere that gets compiled as part of OMR that _can't_ be warning free?

**Comment by rwy0717** [comment]
This is for developers and downstream, people working with toolchains which OMR doesn't compile cleanly with (EG me on my laptop).

**Comment by keithc-ca** [comment]
Thanks. I was hoping we weren't retreating from our goal of warning-free compiles.
