### ISSUE TITLE
SDK and JRE images should only contain production shared libraries

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk9#100]
There are a number of extra shared libraries in the SDK and JRE images. Only the required libraries should be included in these images.

- libjclse7b_29.so is only for Java 8 and should just be excluded

- libgdb_j929.so is for development/debugging and should be put elsewhere

- the following are for testing, and should be put into another location so they can be used by the tests: libSharedClassesNativeAgent.so, libballoon29.so, libbcuwhite.so, libbcvwhite.so, libgptest.so, libhooktests.so, libj9ben.so, libj9lazyClassLoad.so, libj9thrnumanatives29.so, libj9thrtestnatives29.so, libj9unresolved.so, libj9vmtest.so, libjcoregen29.so, libjlmagent29.so, libjniargtests.so, libmemorywatcher29.so, libmigration.so, libosmemory29.so, libsoftmxtest.so, libtestjvmtiA.so, libtestjvmtiB.so, libtestlibA.so, libtestlibB.so, libvmruntimestateagent29.so

Moving the test libraries needs to be coordinated with the test team since the tests will need to find the libraries in the new location. eclipse/openj9#805

FYI ibmruntimes/openj9-openjdk-jdk8#17

**Comment by andrew-m-leonard** [comment]
JDK9 now closed, this has been fixed in JDK11+
