### ISSUE TITLE
Windows Cygwin Setup Issues

### ISSUE THREAD

**Issue by gdams** [ibmruntimes/openj9-openjdk-jdk9#101]
I am having issues setting up Cygwin on our server 2012r2 machines.

The fundamental issue seems to be with CYGPATH:

This is what your internal machines output (courtesy of @vsebe):
```bash
cygpath -s -m -a "C:/Program Files (x86)/Microsoft Visual Studio 12.0"
C:/PROGRA~2/MICROS~1.0
```

This is what our machines output:
```bash
cygpath -s -m -a "C:/Program Files (x86)/Microsoft Visual Studio 12.0"
C:/Program Files (x86)/MICROS~2.0
```

This results in a configure error:
`'C:/program' is not recognized as an internal or external command,`

**Comment by gdams** [comment]
Also to confirm this is what is blocking us from adding Windows binaries to AdoptOpenJDK

**Comment by DanHeidinga** [comment]
@vsebe Can you update this issue with the current status?  Unblocking the Adopt builds is a priority.

**Comment by gdams** [comment]
So I can probably update you there. We have confirmed that we are running the same version of cygwin/cygpath. I have tried taking the cygpath binary that you use and sticking it on the machine but had no luck with that either. We also seemed to nail this down to being an issue with server 2012 only as the command runs fine on server 2008r2

**Comment by DanHeidinga** [comment]
@gdams Can you test with `-d` as well?

ie: `cygpath -d -s -m -a "C:/Program Files (x86)/Microsoft Visual Studio 12.0"`

https://cygwin.com/cygwin-ug-net/cygpath.html

**Comment by vsebe** [comment]
It works fine on our win 2012 R2 Jenkins nodes (internal Jenkins). However, they are different version:
```
$ uname -svr
CYGWIN_NT-6.3 2.9.0(0.318/5/3) 2017-09-12 10:18

```
On the AdoptOpenJDK machines:
```
Administrator@build-win2012-2 ~
$ uname -svr
CYGWIN_NT-6.3-WOW 2.9.0(0.318/5/3) 2017-09-12 10:41

```

**Comment by gdams** [comment]
@vsebe what is the easiest way to do that?

**Comment by bletherhead** [comment]
Just a thought - does `C:\Program Files (x86)` actually have a short (i.e. 8.3) filename on the AdoptOpenJDK machine?
`dir /x c:\` will show you 8.3 filenames and should look something like this:
```
C:\>dir /x c:\
 Volume in drive C has no label.
 Volume Serial Number is BA6A-97E2

 Directory of c:\

27/05/2016  10:56    <DIR>                       apps
15/10/2014  10:47    <DIR>                       cygwin
20/01/2013  18:29    <DIR>                       IBM
14/12/2017  09:55    <DIR>                       NSClient
26/07/2012  07:44    <DIR>                       PerfLogs
12/01/2013  22:35    <DIR>                       Perl
23/11/2017  10:41    <DIR>          PROGRA~1     Program Files
02/03/2017  16:18    <DIR>          PROGRA~2     Program Files (x86)
14/12/2017  13:12    <DIR>                       temp
26/06/2016  12:14    <DIR>                       tmp
19/10/2017  10:51    <DIR>                       Users
14/12/2017  13:12    <DIR>                       Windows
               1 File(s)          3,721 bytes
              17 Dir(s)  68,452,732,928 bytes free
```
`CYGWIN_NT-6.3` and `CYGWIN_NT-6.3-WOW` suggests to me that the internal machine has 64 bit Cygwin installed and the Adopt machine has 32 bit Cygwin installed. However, I've tried your `cygpath` command on 32 and 64 bit installations of Cygwin on internal 2008, 2012 and 2016 machines and got back the expected result on all of them.

**Comment by gdams** [comment]
It looks like I don't
```
 Directory of c:\

12/07/2017  08:13 AM    <DIR>          APACHE~1     apache-ant
12/08/2017  11:20 AM    <DIR>                       cygwin64
12/05/2017  03:26 PM    <DIR>                       Drivers
12/05/2017  02:56 PM    <DIR>                       installs
12/06/2017  01:57 PM    <DIR>                       openjdk
08/22/2013  09:52 AM    <DIR>                       PerfLogs
12/13/2017  06:33 PM    <DIR>                       Program Files
12/07/2017  08:19 AM    <DIR>                       Program Files (x86)
12/05/2017  06:56 PM    <DIR>                       Projects
12/06/2017  01:56 PM    <DIR>          STRAWB~1     Strawberry
05/30/2017  02:11 PM    <DIR>                       sxs
12/05/2017  03:29 PM    <DIR>                       Sysprep
12/08/2017  10:40 AM    <DIR>                       temp
12/07/2017  03:41 PM    <DIR>                       tmp
12/05/2017  12:40 PM    <DIR>                       Users
12/06/2017  05:22 AM    <DIR>                       Windows
```

**Comment by bletherhead** [comment]
You  should be able to set shortnames using fsutil, e.g.   
`fsutil file setshortname "Program Files" "PROGRA~1"`  
You might have to do that in safe mode.
I wonder though why they weren't created when the system was installed

**Comment by DanHeidinga** [comment]
Looking at https://technet.microsoft.com/en-us/library/cc959352.aspx there's a registry entry `NtfsDisable8dot3NameCreation` that determines if short names are created or not.  Changing it requires a reboot.

Worth validating it's set correctly

**Comment by gdams** [comment]
@bletherhead that did it! No need to be in safe mode!

**Comment by gdams** [comment]
test build here: https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_x86-64_windows/9/console

**Comment by gdams** [comment]
hmm test build failed... any idea why?

**Comment by DanHeidinga** [comment]
Is the `* All command lines available in /cygdrive/c/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/make-support/failure-logs.` log file available?  There isn't enough context in the jenkins console log to hazard a guess as to why the build failed.

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_x86-64_windows/ws/openjdk/build/windows-x86_64-normal-server-release/make-support/failure-logs/ (you may need to be logged into our ci to see the files)

**Comment by DanHeidinga** [comment]
Thanks @gdams.  @vsebe and I have been looking at the commandlines in those files and as the commands are from the OpenJDK makefiles, she's going to test a plain openjdk build on the machine.

We've been focusing on the "fixpath" command.

**Comment by vsebe** [comment]
The same failure is encountered when building OpenJDK9:

> Compiling 31 files for BUILD_JRTFS
> An exception has occurred in the compiler (9-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
> java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator
> 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors.iterator(JavacProcessingEnvironment.java:814)
> 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.atLeastOneProcessor(JavacProcessingEnvironment.java:615)
> 	at com.sun.tools.javac.main.JavaCompiler.initProcessAnnotations(JavaCompiler.java:1124)
> 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:908)
> 	at com.sun.tools.javac.main.Main.compile(Main.java:302)
> 	at com.sun.tools.sjavac.comp.SjavacImpl.compile(SjavacImpl.java:117)
> 	at com.sun.tools.sjavac.comp.PooledSjavac.lambda$compile$0(PooledSjavac.java:63)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> cppInterpreter.cpp
> cpCache.cpp
> cppInterpreterGenerator.cpp
> make[3]: *** [CompileTools.gmk:48: /cygdrive/c/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/jdk9/build/windows-x86_64-normal-server-release/buildtools/jdk_tools_classes/_the.BUILD_TOOLS_JDK_batch] Error 4
> make[2]: *** [make/Main.gmk:85: buildtools-jdk] Error 2
> make[2]: *** Waiting for unfinished jobs....
> debug.cpp
> debugInfo.cpp
> concurrentMarkSweepGeneration.cpp
> debug_x86.cpp
> debugInfoRec.cpp
> decoder_elf.cpp
> decoder.cpp
> An exception has occurred in the compiler (9-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
> java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator
> 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors.iterator(JavacProcessingEnvironment.java:814)
> 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.atLeastOneProcessor(JavacProcessingEnvironment.java:615)
> 	at com.sun.tools.javac.main.JavaCompiler.initProcessAnnotations(JavaCompiler.java:1124)
> 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:908)
> 	at com.sun.tools.javac.main.Main.compile(Main.java:302)
> 	at com.sun.tools.sjavac.comp.SjavacImpl.compile(SjavacImpl.java:117)
> 	at com.sun.tools.sjavac.comp.PooledSjavac.lambda$compile$0(PooledSjavac.java:63)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> decoder_windows.cpp
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> depChecker_x86.cpp
> An exception has occurred in the compiler (9-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
> java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator
> 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors.iterator(JavacProcessingEnvironment.java:814)
> 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.atLeastOneProcessor(JavacProcessingEnvironment.java:615)
> 	at com.sun.tools.javac.main.JavaCompiler.initProcessAnnotations(JavaCompiler.java:1124)
> 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:908)
> 	at com.sun.tools.javac.main.Main.compile(Main.java:302)
> 	at com.sun.tools.sjavac.comp.SjavacImpl.compile(SjavacImpl.java:117)
> 	at com.sun.tools.sjavac.comp.PooledSjavac.lambda$compile$0(PooledSjavac.java:63)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> make[3]: *** [JrtfsJar.gmk:52: /cygdrive/c/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/jdk9/build/windows-x86_64-normal-server-release/support/jrtfs_classes/_the.BUILD_JRTFS_batch] Error 4
> dependencyContext.cpp
> make[2]: *** [make/Main.gmk:335: jrtfs-jar] Error 2
> make[3]: *** [CompileInterimRmic.gmk:47: /cygdrive/c/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/jdk9/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.rmic/_the.BUILD_INTERIM_RMIC_batch] Error 4
> make[2]: *** [make/Main.gmk:79: interim-rmic] Error 2
> dependencies.cpp
> defNewGeneration.cpp

**Comment by vsebe** [comment]
fixpath output sample:

```
fixpath converted line >c:/openjdk/jdk1.8.0_151/bin/java -XX:+UseSerialGC -Xms32M -Xmx512M -XX:TieredStopAtLevel=1 -Duser.language=en -Duser.country=US -Xbootclasspath/p:c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/java.compiler;c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.compiler;c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.jdeps;c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.javadoc -cp c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.compiler com.sun.tools.sjavac.Main --server:portfile=c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/make-support/javacservers/server.port,id=BUILD_TOOLS_JDK,sjavac=c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/configure-support/bin/fixpath.exe%20-c%20--detach%20c:/openjdk/jdk1.8.0_151/bin/java%20-d64%20-Xms512M%20-Xmx2048M%20-Xbootclasspath/p:c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/java.compiler;c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.compiler;c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.jdeps;c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.javadoc%20-cp%20c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/override_modules/jdk.compiler%20com.sun.tools.sjavac.Main -g -source 8 -target 8 -XDignore.symbol.file=true -XDstringConcat=inline -Xlint:all,-deprecation,-removal,-unchecked,-rawtypes,-cast,-serial,-dep-ann,-static,-fallthrough,-try,-varargs,-empty,-finally -Xlint:-options -implicit:none -d c:/Users/jenkins/workspace/openjdk9_openj9_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/buildtools/jdk_tools_classes "@C:\cygwin64\tmp\atfile_a01988"<
An exception has occurred in the compiler (9-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors.iterator(JavacProcessingEnvironment.java:814)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.atLeastOneProcessor(JavacProcessingEnvironment.java:615)
        at com.sun.tools.javac.main.JavaCompiler.initProcessAnnotations(JavaCompiler.java:1124)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:908)
        at com.sun.tools.javac.main.Main.compile(Main.java:302)
        at com.sun.tools.sjavac.comp.SjavacImpl.compile(SjavacImpl.java:117)
        at com.sun.tools.sjavac.comp.PooledSjavac.lambda$compile$0(PooledSjavac.java:63)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by gdams** [comment]
any progress with this?

**Comment by DanHeidinga** [comment]
@gdams On Adopt, I see the OpenJDK builds are running on ` build-1and1-win2008r2-1` while the OpenJ9 build is on `build-softlayer-x64-windows-2012r2-1`.   Can we run an OpenJ9 build on the win2008 machine?

**Comment by gdams** [comment]
that machine doesn't currently have visual studio 2013 on it. We are also planning to drop it and start building on a pair of 2012 machines

**Comment by DanHeidinga** [comment]
@vsebe did an experiment compiling OpenJDK on the 2012 machine about 3 comments up (https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/101#issuecomment-352079256) which shows that the OJDK build fails on the 2012 machine as well.

Has Adopt successfully built OJDK on a 2012 machine?  I'm starting to suspect a machine config issue.

**Comment by gdams** [comment]
no, this is a brand new machine, It's more than likely a machine config issue :)

**Comment by vsebe** [comment]
The buildtools targets that requires the new compiler fails (this is not OpenJ9 code).
The fixpath.exe seems to work correctly, the bootclasspath and classpath for the new compiler are set (see INTERIM_LANGTOOLS_OVERRIDE_MODULES_ARGS and INTERIM_LANGTOOLS_ARGS in spec.gmk.in)

**Comment by DanHeidinga** [comment]
@vsebe Any update on this?

**Comment by vsebe** [comment]
If the boot-jdk path does not contains any space, it works. Looks the short paths are not properly set.

**Comment by vsebe** [comment]
Path too long. AdoptOpnJDK build: https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_x86-64_windows/14/console
https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_x86-64_windows/14/console

'/cygdrive/c/Users/jenkins/jdk9_j9/openjdk/build/windows-x86_64-normal-server-release/images/jdk' found

```
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc..openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Windows Server 2012 R2 amd64-64 Compressed References 20180115_14 (JIT enabled, AOT enabled)
OpenJ9   - bb5a8c43
OMR      - 3a1762f5
OpenJDK  - be5903df5 based on jdk-9+181)

```

**Comment by vsebe** [comment]
Last 5 builds passed:
https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_x86-64_windows/18/
Closing issue.

**Comment by jmarrero** [comment]
Hi, there is still no Windows version at https://adoptopenjdk.net. Is this intended, if so when a windows release is expected?

**Comment by pshipton** [comment]
@jmarrero There is a Windows download for Java 9 in the nightly builds https://adoptopenjdk.net/nightly.html?variant=openjdk9-openj9

**Comment by johnoliver** [comment]
For anyone coming back to this issue later, I cannot confirm the length of the path is definitely the problem, but moving the build workspace to one with a shorter path does appear to have worked for me.
