### ISSUE TITLE
AO8/J9 s390x builds do not work out of the box

### ISSUE THREAD

**Issue by sxa555** [ibmruntimes/openj9-openjdk-jdk9#105]
I presume this is somewhere around the `redirector.c` code within `openj9`

if you download the s390x AO8/J9 builds from www.AdoptOpenJDK.net and try to run it you get this error:

```
jcktest@csz25074:/dev/shm/jdk8u152-b16/bin$ ./java -version
Error: missing `server' JVM at `/dev/shm/jdk8u152-b16/jre/lib/s390x/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
jcktest@csz25074:/dev/shm/jdk8u152-b16/bin$ 
```
Creating a symbolic link from `jre/lib/s390x/server` to `jre/lib/s390x/j9vm` allows the JVM to start up, so somewhere along the lines in the build it's still looking for `libjvm.so` in HotSpot's location.

**Comment by sxa555** [comment]
Wrong repo - closing

**Comment by pshipton** [comment]
Its caused by the jvm.cfg file, which needs to contain

```
-j9vm KNOWN
-server IGNORE
```
