### ISSUE TITLE
Usage screen of get_source scripts reference github.ibm.com

### ISSUE THREAD

**Issue by sxa555** [ibmruntimes/openj9-openjdk-jdk9#13]
References in https://github.com/ibmruntimes/openj9-openjdk-jdk9/blob/openj9/get_source.sh and also get_j9_source.sh to github.ibm.com should be changed to the accessible locations on github.com

**Comment by AdamBrousseau** [comment]
waiting to be merged in #5

**Comment by mstoodle** [comment]
Merged now. Thanks @sxa555 and @AdamBrousseau ~
