### ISSUE TITLE
ARM misplaced libraries

### ISSUE THREAD

**Issue by JamesKingdon** [ibmruntimes/openj9-openjdk-jdk9#132]
I just tried a build with the latest changes (openj9 branch as of Feb 24 AM) and it seems a couple of the libraries aren't getting copied to the expected locations, instead they are in subdirectories of lib/default:

j9vm_b156/libjvm.so
jcl/cl_se9/libjclse9_29.so

If I copy or symlink these into lib/default the JVM starts up ok.

**Comment by jdekonin** [comment]
Likely due to #131, fyi @keithc-ca

**Comment by keithc-ca** [comment]
I expect @jdekonin is correct. It should be straight-forward to fix.

**Comment by JamesKingdon** [comment]
#131 is a huge improvement, this looks so much cleaner now.

**Comment by keithc-ca** [comment]
Thanks, @JamesKingdon. I think it's just a matter of a dropped call to `$(notdir)`.

**Comment by keithc-ca** [comment]
Fixed via #134: closing.

**Comment by JamesKingdon** [comment]
Just got a chance to try out the changes, all looks good now. Many thanks!
