### ISSUE TITLE
OpenJ9 Java 9 extension doesn't have latest level

### ISSUE THREAD

**Issue by JasonFengJ9** [ibmruntimes/openj9-openjdk-jdk9#136]
Class `jdk.internal.misc.Unsafe` in current `OpenJ9` branch still refers obsoleted method `allocateDBBMemory, allocateDBBMemory, freeDBBMemory` such as https://github.com/ibmruntimes/openj9-openjdk-jdk9/blob/openj9/jdk/src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template#L100, while the `master` branch refers to `allocateMemory, allocateMemory, freeMemory` instead such as https://github.com/ibmruntimes/openj9-openjdk-jdk9/blob/master/jdk/src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template#L94.

This suggests `OpenJ9 Java 9` branch doesn't have latest level updates.

FYI: @theresa-m @DanHeidinga @pshipton

**Comment by DanHeidinga** [comment]
My understanding is that `master` branch contains the unpatched OpenJDK code while the `openj9` branch includes the modifications necessary to run OpenJ9.

**Comment by JasonFengJ9** [comment]
Right, that's my understanding as well. The difference shown in this issue is not due to the modification to run OpenJ9, it just doesn't get latest OpenJDK update. Latest `OpenJDK Java 9 b181` replaced `allocateDBBMemory, allocateDBBMemory, freeDBBMemory` with `allocateMemory, allocateMemory, freeMemory` though I am not sure exactly when the API were changed.

**Comment by DanHeidinga** [comment]
The DBB family of functions (`allocateDBBMemory` and friends) are OpenJ9 extensions.  They haven't been in OpenJDK (yet)

**Comment by JasonFengJ9** [comment]
Thanks @DanHeidinga for the clarification. 
Closing this issue accordingly.
