### ISSUE TITLE
Use --with-jvm-variants for identifying a 64 vs 64-compressedrefs build

### ISSUE THREAD

**Issue by jdekonin** [ibmruntimes/openj9-openjdk-jdk9#20]
Currently binaries are generating for the 64bit compressed platforms (default) and not the 64bit version.  Using --with-jvm-variants would appear to be the option that should detail which one or both versions should be created.

**Comment by archanaNogriya** [comment]
@jdekonin 
Where I can find what flag we need to pass which can create binary for noncompress 64 build? and where?
The JVM variants to build from, comma separated list that can include: server, client, kernel, zero and zeroshark.

**Comment by archanaNogriya** [comment]
However client VM is only available on 32-bit systems

**Comment by jdekonin** [comment]
I don't see this as a simple enable a flag fix.  Rather create (or maybe repurpose existing) flag(s) that will provide make instructions as to what set of binaries need to be generated.

Currently configure detects the 64bit platform and architecture and then configuration translates that to the J9 cmprssptrs version.  See closed/autoconf/custom-hook.m4.

Turning on 32bit versions shouldn't be difficult, but that should be done under a different issue and only once we have some sort of story around how to specify cmprssptrs or non-cmprssptrs.

**Comment by groeges** [comment]
There are several issue that are related to this issue:

https://github.com/eclipse/openj9/issues/479
https://github.com/eclipse/openj9/issues/643

These are being discussed and worked on.  
Main thought in issue #643 is to make this a runtime choice and not a compile time choice.

**Comment by DanHeidinga** [comment]
> Main thought in issue #643 is to make this a runtime choice and not a compile time choice.

Making this a runtime choice is at least 6 months of work, and will likely negatively effect startup performance.  I think we need to continue to pursue the combining a compressed & non-compressed into a single package.
