### ISSUE TITLE
jdmpview and traceformat executables

### ISSUE THREAD

**Issue by jdekonin** [ibmruntimes/openj9-openjdk-jdk9#22]
The OpenJ9 build doesn't create the jdmpview and traceformat executables. They should be created in the same way other executables like javac, javah, etc are created.

The executables should run the following main classes, however the module names may change in the future.

java -m com.ibm.dtfjview/com.ibm.jvm.dtfjview.DTFJView

bin/java -m com.ibm.traceformat/com.ibm.jvm.traceformat.TraceFormat

**Comment by Bluevisitor** [comment]
Update: a number of files create executables, but I think the one that generates javac is:
jdk/make/launcher/Launcher-jdk.compiler.gmk

This uses the file LauncherCommon.gmk in the same directory, example here:

`$(eval $(call SetupBuildLauncher, javac, \
   MAIN_CLASS := com.sun.tools.javac.Main, \
   JAVA_ARGS := --add-modules ALL-DEFAULT, \
   CFLAGS := -DEXPAND_CLASSPATH_WILDCARDS, \
))`

If we want executables for jdmpview and traceformat, I think we need to add either a seperate file, or add to one of the existing files. To minimise the required changes, the latter is probably preferable.

I'm adding it to the Launcher-jdk.compiler.gmk in my local sandbox for now, to test the theory. Here's the first draft of the code:

`$(eval $(call SetupBuildLauncher, jdmpview, \
   MAIN_MODULE := com.ibm.dtfjview, \
   MAIN_CLASS := com.ibm.jvm.dtfjview.DTFJView, \
   CFLAGS := -DEXPAND_CLASSPATH_WILDCARDS, \
))

$(eval $(call SetupBuildLauncher, traceformat, \
   MAIN_MODULE := com.ibm.traceformat, \
   MAIN_CLASS := com.ibm.jvm.traceformat.TraceFormat, \
   CFLAGS := -DEXPAND_CLASSPATH_WILDCARDS, \
))`

Attempting a build now.

**Comment by Bluevisitor** [comment]
The build appears to have succeeded, and generated the required executables.

A standard "run the executables with poorly formatted options and make sure they print their help options" test worked, proving that at least some of their code executed properly. If any other tests exist for these executables, I recommend arranging for them to be run.

I'm unassigning this issue now, as I have next week off, so someone else can pick up the baton.

**Comment by Bluevisitor** [comment]
After reviewing the existing files, I believe that the Launcher-jdk.jcmd.gmk file is the best location for the code that generates these executables, on the basis that that gmk file already generates the executables for jinfo and jmap, which are (and use) debugging tools.

I'm running a build now with the new code added to that file. While that's running I plan to seek out any existing testing we have for these executables (to ensure we're generating them correctly).

**Comment by pshipton** [comment]
Note J9 doesn't currently support jinfo, jmap and others. We could turn off generation of the unsupported modules, I've created another issue #52 for that.

**Comment by Bluevisitor** [comment]
So you'll probably be removing or excluding the code that generates their executables as well, I imagine. 

Would it be possible to execute the file along with the other executable-generating files, but simply exclude the bits we don't want?

If not, let me know, as I will need to put the code that generates the jdmpview and traceformat executables in another file.

**Comment by pshipton** [comment]
From a quick look, using another file would be better considering every executable in Launcher-jdk.jcmd.gmk is unsupported by OpenJ9. Plus we want to extend the build rather than modify existing files (except to add extensions hooks into existing files).

**Comment by Bluevisitor** [comment]
That should work for this issue, but issue 52 may have problems. See that issue for my concerns.

**Comment by Bluevisitor** [comment]
The code for this is ready, and has been for a while now (see https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/55). I'm working on running tests to verify that they work (beyond executable --help).

I've identified VM_Promotion.cmdLineTester_callsitedbgddrext as a good jdmpview test. Working on running it.

**Comment by pshipton** [comment]
Note OpenJ9 doesn't support DDR yet, jdmpview on OpenJ9 will be extremely limited functionality. The task was to create the executables, and it seems this is completed. As long as they run the correct main class I think this task can be considered complete.

**Comment by Bluevisitor** [comment]
Seems fair. I ran it past Andrew as well, to make sure I'm not accepting this just because it's easier.

I've got a clean build running now, to make sure what I'm committing works as well as my local copy (which has other changes). If that works, I'll ask someone to approve the PR and merge.

**Comment by pshipton** [comment]
Seems you are already convinced, but just for the record - I expect any problems found from running the executables, besides problems related to running the right main class, would be OpenJ9 Issues and not resolved under this Issue on the extensions.

**Comment by Bluevisitor** [comment]
Ok, the build is finished, and the produced executables are calling the right classes.

pshipton and yongja79 have reviewed and approved. yongja79 had trouble with the review system, but you'll see his review down the bottom, to prove he reviewed it.

**Comment by groeges** [comment]
@pshipton Should these same executable changes (add traceformat, jextract & jdmpview, and remove jstatd & jcmd) be made on the openj9-openjdk-jdk8 extensions also.
