### ISSUE TITLE
Pull Request builds (z/p - sanity)

### ISSUE THREAD

**Issue by AdamBrousseau** [ibmruntimes/openj9-openjdk-jdk9#27]
Similar to eclipse/openj9#91

- Builds should compile and run the sanity test target.
- [Linux-ppc64le](https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le-OpenJDK/)
- [Linux-s390x](https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le-OpenJDK/)
- Need a list of users to whitelist (allowed to request builds).
- Trigger phrase `jenkins test sanity` case insensitive for all platforms
    - `jenkins test sanity plinux`
    - `jenkins test sanity zlinux`
- Trigger based on Github hook (not polling) URL: https://ci.eclipse.org/openj9/ghprbhook/

**Comment by AdamBrousseau** [comment]
@andrew-m-leonard I need a list of people to whitelist and I need an admin to create a webhook on the repo

**Comment by ben-walsh** [comment]
@AdamBrousseau Initial members of such a whitelist are identified here - https://github.com/orgs/ibmruntimes/teams/openj9/members.

Question - do we want to go down the route of whitelisting rather than blacklisting ?

How likely are those wanting to abuse the system to go to the effort of creating a PR, making a suitably destructive change and trigger enough builds for it to be a problem ?

The more "friction" with these sort of things for both this repo and openj9 repo, the lower the participation rate in the projects.

**Comment by AdamBrousseau** [comment]
@ben-walsh that isn't a publicly visible team so I cannot see it as I am not a member.
I am setting it up this way since this is the way it has already been setup on the openj9 repo.
I wouldn't say that having a whitelist of users who can request PR builds would deter contributors. I would actually argue that a whitelist is more appropriate in the case of this repo since we are only accepting contributions from IBMers to this repo. I also think it's common practice in open source communities to have a whitelist. It's a security concern as well as a farm load concern.

**Comment by ben-walsh** [comment]
Ah. Here's the current content at that page ...

```
OpenJ9 @ibmruntimes/openj9
Team working on the Extensions for OpenJDK for Eclipse OpenJ9
 Members 10  Teams 0  Repositories 1
 
Find a member…
 10 members   0 child team members Role 
 davew16	Dave Williams  davew16
 gibfahn	Gibson Fahnestock  gibfahn Maintainer
 keithc-ca	Keith W. Campbell  keithc-ca
 jdekonin	jdekonin
 archanaNogriya	archanaNogriya
 ben-walsh	ben-walsh
 Bluevisitor	Bluevisitor
 andrew-m-leonard	andrew-m-leonard  Maintainer
 jonathanwoodford	jonathanwoodford
 yongja79	yongja79
```

**Comment by ben-walsh** [comment]
Fair enough of the security/load concerns - perhaps we've had differing previous experiences in this regard.

**Comment by AdamBrousseau** [comment]
Updated the whitelist with the names above, please let me know when the hook is created or if you have any questions about it.

**Comment by AdamBrousseau** [comment]
Thnaks @jdekonin for adding the hook. This should be operational now. Please post any immediate issues here.
