### ISSUE TITLE
Freemarker jar cannot be found if location includes a tilde (~)

### ISSUE THREAD

**Issue by Bluevisitor** [ibmruntimes/openj9-openjdk-jdk9#29]
This command works:

bash ./configure --with-freemarker-jar=/root/freemarker.jar

This command does not:

bash ./configure --with-freemarker-jar=~/freemarker.jar

However, the latter is indicated as the correct format on the eclipse openj9 build instructions page:

https://www.eclipse.org/openj9/oj9_build.html

Note: "echo ~" is "/root", and "echo $0" is "/bin/bash".

Also, Luc Maisons discovered this behaviour:

root@03aeb33e669a:\~# bash ./echo.sh --with-freemarker-jar=\~/freemarker.jar
--with-freemarker-jar=\~/freemarker.jar
root@03aeb33e669a:\~# bash ./echo.sh --with-freemarker-jar= \~/freemarker.jar
--with-freemarker-jar= /root/freemarker.jar

So my working theory is that bash isn't expanding the tilde, and Joe's work in #25 can't find the freemarker jar as a result.

Joe has offered to revert the change for time being, until a fix can be found.

**Comment by ben-walsh** [comment]
Attempting to recreate this.

@Bluevisitor Please can you provide the output of ...
```
env
```
... on the system where you attempted the command ...
```
bash ./configure --with-freemarker-jar=~/freemarker.jar
```

**Comment by ben-walsh** [comment]
Hmmmm, my initial theory that having a SHELL environment variable set to /bin/sh causes the problem, has been proven incorrect - at least outside of the docker image. Potentially there is different behaviour when inside the docker image. To be tested.

**Comment by lmaisons** [comment]
This is the experiment referred to above:
```
root@03aeb33e669a:~# cat > echo.sh
echo "$@"
root@03aeb33e669a:~# cat echo.sh
echo "$@"
root@03aeb33e669a:~# bash ./echo.sh --with-freemarker-jar=~/freemarker.jar
--with-freemarker-jar=~/freemarker.jar
root@03aeb33e669a:~# bash ./echo.sh --with-freemarker-jar= ~/freemarker.jar
--with-freemarker-jar= /root/freemarker.jar
```
Reading https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html and http://wiki.bash-hackers.org/syntax/expansion/tilde it seems bash is only supposed to expand tildes at the beginning of a word, or as part of a variable assignment.  Bash's parsing is not 100% as bash will expand:
```
[lmaisons@statik:~]$ cat echo.sh
echo "$@"
[lmaisons@statik:~]$ bash ./echo.sh foo=~
foo=/home/lmaisons
```
and will even expand:
```
[lmaisons@statik:~]$ bash ./echo.sh with_freemarker_jar=~/freemarker.jar
with_freemarker_jar=/home/lmaisons/freemarker.jar
```
But it stops doing so as soon as a dash character is introduced:
```
[lmaisons@statik:~]$ bash ./echo.sh with-freemarker-jar=~/freemarker.jar
with-freemarker-jar=~/freemarker.jar
[lmaisons@statik:~]$ bash ./echo.sh with_freemarker_jar-=~/freemarker.jar
with_freemarker_jar-=~/freemarker.jar
[lmaisons@statik:~]$ bash ./echo.sh -with_freemarker_jar=~/freemarker.jar
-with_freemarker_jar=~/freemarker.jar
```

**Comment by keithc-ca** [comment]
Bash is documented to do tilde expansion of 'value' in 'name=value' (where name is a legal variable name and so doesn't contain a dash), but as I read the documentation, it should only happen for (environment variable) definitions appearing _before_ the command name on the command line, but perhahs bash thinks it's being helpful for commands like:
`
make FREEMARKER=~/freemarker.jar
`
The simplest solution in my opinion is to improve the documentation to avoid suggesting commands that don't work reliably. The guidance should be:
`
configure --with-freemarker-jar=$HOME/freemarker.jar
`
which will work with just about any shell.

**Comment by jdekonin** [comment]
@SueChaplain can you please advise once documentation has been updated so I can redo/revert the work performed under #25 and #28?  Thanks.

**Comment by SueChaplain** [comment]
@jdekonin Hi Joe. Peter has now refreshed the site. Path now fixed. Sorry for the delay.

**Comment by keithc-ca** [comment]
The documentation at https://www.eclipse.org/openj9/oj9_build.html has been updated. The problem described here does not occur if that advice is taken.

**Comment by Bluevisitor** [comment]
Good work guys. Thanks!
