### ISSUE TITLE
Binary not recognising / stating use of open source packages.

### ISSUE THREAD

**Issue by jonathanwoodford** [ibmruntimes/openj9-openjdk-jdk9#3]
The Eclipse OpenJ9 project uses several open source projects.  These are detailed in the longabout.html file.  I have noticed that once compiled via the Extensions for OpenJDK for Eclipse OpenJ9, the binary is not preserving recognition of this open source.

At a minimum we should include the longabout.html file and ensure that users understand that this is specifically for the openJ9 component.  Ideally we should append it to the OpenJDK equivalent file.

**Comment by mstoodle** [comment]
@jonathanwoodford I guess you're referring to the fact that there is no section under jre/legal for Eclipse OpenJ9? Or is there another spot you're referring to?

**Comment by jonathanwoodford** [comment]
That's right.  We need to list Eclipse OpenJ9 and it's associated open source.
