### ISSUE TITLE
make exploded-images doesn't work

### ISSUE THREAD

**Issue by mgaudet** [ibmruntimes/openj9-openjdk-jdk9#34]
I just did a build in a container, and experienced the following error: 

```
Creating support/modules_cmds/jdk.xml.bind/schemagen from 1 file(s)
Creating support/modules_cmds/jdk.xml.bind/xjc from 1 file(s)
Creating support/modules_cmds/jdk.xml.ws/wsgen from 1 file(s)
Creating support/modules_cmds/jdk.xml.ws/wsimport from 1 file(s)
Compiling 4 files for BUILD_JIGSAW_TOOLS
Error: missing `j9vm' JVM at `/sandbox/build/linux-x86_64-normal-server-release/jdk/lib/j9vm/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
make[3]: *** [/sandbox/build/linux-x86_64-normal-server-release/jdk/_packages_attribute.done] Error 4
ExplodedImageOptimize.gmk:40: recipe for target '/sandbox/build/linux-x86_64-normal-server-release/jdk/_packages_attribute.done' failed
make/Main.gmk:358: recipe for target 'exploded-image-optimize' failed
make[2]: *** [exploded-image-optimize] Error 1

ERROR: Build failed for target 'default (exploded-image)' in configuration 'linux-x86_64-normal-server-release' (exit code 2) 
Stopping sjavac server
```

This is because if you type `make`, with no sub target, the default is `exploded-images`, which appears to not work.

**Comment by mgaudet** [comment]
Container: `docker build -t openj9build openj9/buildenv/docker/jdk9/x86_64/ubuntu16/`

Docker Command: 

```
docker run --rm -it  -v$PWD:/sandbox -v$HOME/open/jdk-9+181.openj9:/sdk openj9build  /bin/bash
```

Configured with free marker from `$HOME/freemarker.jar`, and using OpenJ9 as the boot-idk.

**Comment by mgaudet** [comment]
For references, here's my repo revisions: 

openJ9-openjdk-jdk9: b468fb8a4def0697cd2b49c5537d4c4529f50043
omr: 3271be89f2df16683616fe0e38c85693cea982bb
openJ9: c01ae1b0aac52f8cc2329e5057fe32e4580ed44e

**Comment by keithc-ca** [comment]
You don't want to use the default make target, you want to say `make images` (unless you told configure that should be your default target). You could also do as advised at https://www.eclipse.org/openj9/oj9_build.html and say `make all`.

**Comment by mgaudet** [comment]
So should I perhaps open a different item that the default make target is broken?

**Comment by keithc-ca** [comment]
I don't think the default make target is broken  - it's what you asked for at step configure step. This surprised me at first too, but I've come to accept it.
`bash configure --help` says
```
  --with-default-make-target
                          set the default make target [exploded-image]
```
That means `make` is the same as saying `make exploded-image` which is apparently not what we would have expected. I imagine you'll have more success using `bash configure  --with-default-make-target=images` than opening an issue about the default make target.

In any case, I think this issue should be closed.

**Comment by mgaudet** [comment]
Do we care if `exploded-image` is broken? Should that get an issue? in the mean time, I'll open an issue with the website suggesting that be added as a configure arg.

**Comment by keithc-ca** [comment]
Perhaps this ought to be re-purposed as a request to make `make exploded-image` functional?

**Comment by mgaudet** [comment]
Edited description and title.

**Comment by mgaudet** [comment]
(I'll leave it up to @ben-walsh if pulling the invalid label makes sense now)

**Comment by keithc-ca** [comment]
I suggest removing the 'invalid' label _does_ make sense.

**Comment by ben-walsh** [comment]
I think this is a further symptom of https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/21. Need to confirm.

**Comment by ben-walsh** [comment]
Further investigation suggests this is *not* a further symptom of #21.

**Comment by keithc-ca** [comment]
I believe I have JDK11 working properly; backporting to earlier versions should be relatively painless.
