### ISSUE TITLE
'Java -version' missing 'based on' reference / string. 

### ISSUE THREAD

**Issue by jonathanwoodford** [ibmruntimes/openj9-openjdk-jdk9#4]
'Java -version' reports the following (below).  It seems to be missing a reference to what it is 'based on'.  Also, is "9-internal" that correct string for the version?

openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.root.openj9-openjdk-jdk9)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170913_000000 (JIT enabled, AOT enabled)
J9VM - d567e49
JIT  - d567e49
OMR  - 617de12
OpenJDK  - f35a4ea based on )

**Comment by andrew-m-leonard** [comment]
My build this morning:
admin@fce441e75a84:~/ccm/openj9Public$ ./build/linux-x86_64-normal-server-release/images/jdk/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc..openj9Public)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170914_000000 (JIT enabled, AOT enabled)
J9VM - 790f81d
JIT  - 790f81d
OMR  - 617de12
OpenJDK  - f35a4ea based on jdk-9+181)

**Comment by andrew-m-leonard** [comment]
@jonathanwoodford Jonathan, please re-clone openj9 now that I have added the missing "tags", then re-run your bash configure ... script. Then see if the variable has been substituted in:
  cat build/linux-x86_64-normal-server-release/custom-spec.gmk
look for OPENJDK_TAG
then re-build and see if it looks okay please.

**Comment by mstoodle** [comment]
I still see this problem in the builds performed by the AdoptOpenJDK build scripts. I believe the problem is that they only do a shallow clone (along with fetching the tags) and the git-fu we currently use to identify the latest build tag doesn't work with a shallow clone. I've worked out a fix and will push shortly.

**Comment by jonathanwoodford** [comment]
I am now seeing a based on string:
root@jonathan-openj9:~/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/images/jre/bin# ./java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.root.openj9-openjdk-jdk9)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170915_000000 (JIT enabled, AOT enabled)
J9VM - cea1ed7
JIT  - cea1ed7
OMR  - 617de12
OpenJDK  - 83f5cd0 based on jdk-9+181)

**Comment by FireBurn** [comment]
I'm seeing a similar issue:

java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (IcedTea 3.5.1) (Gentoo icedtea-3.5.1)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

It doesn't like the _JAVA_OPTIONS line coming first

**Comment by mstoodle** [comment]
@FireBurn that doesn't look like OpenJDK with OpenJ9. We don't (yet) have Java 8 support with OpenJ9 (it will come, don't worry!) so that's the key clue :) .
> openjdk version "1.8.0_144"

**Comment by FireBurn** [comment]
The check seems to be for 1.8 or 1.9

checking for version string... 9-internal+0-adhoc.fireburn.openj9-openjdk-jdk9
configure: Found potential Boot JDK using JAVA_HOME
configure: Potential Boot JDK found at /etc/java-config-2/current-system-vm is incorrect JDK version (Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel); ignoring
configure: (Your Boot JDK must be version 8 or 9)

**Comment by mstoodle** [comment]
Ah, ok, i had misinterpreted the issue you're reporting, which is different than this issue. Would you please open a new issue for the problem you're seeing (trying to pass additional Java options in the configure step, assuming that's what you're trying to do) ?
