### ISSUE TITLE
cannot check for freemarker existence when cross compiling

### ISSUE THREAD

**Issue by AlexBudesteanu** [ibmruntimes/openj9-openjdk-jdk9#40]
Hello,

I am trying to cross-compile OpenJ9 for armhf.
I have followed the guidelines [here](url) and I have managed to get to a point where I get this error:

> checking for /root/freemarker.jar... configure: error: cannot check for file existence when cross compiling
configure exiting with result code 1

The command that generated it is: 

> root@091727dd6d99:~/openj9-openjdk-jdk9# bash ./configure --with-freemarker-jar=/root/freemarker.jar --openjdk-target=arm-linux-gnueabihf --with-sys-root=/home/root/rpi-buildroot/host/usr/arm-buildroot-linux-gnueabi/sysroot --with-tools-dir=/home/root/rpi-buildroot/host --with-abi-profile=arm-vfp-hflt

**Comment by jdekonin** [comment]
Hi @AlexBudesteanu, thanks for raising this issue.  I haven't tried working in changes for arm myself as yet.  I have aided a few others with pointers though.  See eclipse/openj9#53 for some more details.

I think that the problem might be with a recent AC_CHECK_FILE that was added (by me).  Would you be able to try the changes I have add to my fork?  jdekonin/openj9? ...same as changes under #41.

**Comment by jdekonin** [comment]
@AlexBudesteanu #41 has been merged.  Please advise if this doesn't resolve the error that you are seeing.

**Comment by AlexBudesteanu** [comment]
Hi @jdekonin! I confirm that your changes fix the mentioned issue. Thank you very much!
