### ISSUE TITLE
WIP: Numa check breaks windows configuration

### ISSUE THREAD

**Issue by vsebe** [ibmruntimes/openj9-openjdk-jdk9#42]
Numa check resets the user compiler to GNU gcc instead of MSVS.

Run configure for windows/cygwin:
`bash configure --disable-warnings-as-errors --with-toolchain-version=2013 --with-toolchain-type=microsoft ...`
...
configure: Found Visual Studio installation at /cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/ using VS120COMNTOOLS variable
configure: Found Microsoft Visual Studio 2013
configure: Rewriting VS_ENV_CMD to "/cygdrive/c/progra~2/micros~1.0/vc/bin/amd64/vcvars64.bat"
configure: Trying to extract Visual Studio environment variables
configure: Setting extracted environment variables
checking for Visual Studio variables... ok
configure: Rewriting ipath to "/cygdrive/c/progra~2/micros~1.0/vc/include"
configure: Rewriting ipath to "/cygdrive/c/progra~2/micros~1.0/vc/atlmfc/include"
...
configure: Rewriting libpath to "/cygdrive/c/progra~2/micros~1.0/vc/lib/amd64"
configure: Rewriting libpath to "/cygdrive/c/progra~2/wi3cf2~1/8.1/lib/winv6.3/um/x64"
configure: Rewriting libpath to "/cygdrive/c/progra~2/micros~1.0/vc/atlmfc/lib/amd64"
**configure: Will use user supplied compiler CC=gcc**
checking for gcc... /usr/bin/gcc
checking resolved symbolic links for CC... no symlink
configure: The C compiler (located as /usr/bin/gcc) does not seem to be the required microsoft compiler.
configure: The result from running it was: "gcc: fatal error: no input files"
configure: error: A microsoft compiler is required. Try setting --with-tools-dir.
configure exiting with result code 1

Expect to use MS c compiler:
e.g.
configure: Using microsoft C compiler version 18.00.40629 [Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64]

**Comment by mgaudet** [comment]
You can make your text show up preformatted by either fencing it with three backticks, or spacing with four spaces: 

    ```
    fenced code shows up pre
    ```

```
    four spaces also 
    leads to pre
```

See more in the GitHub [Guide to Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
