### ISSUE TITLE
Remove dependency on mingw for windows platform

### ISSUE THREAD

**Issue by vsebe** [ibmruntimes/openj9-openjdk-jdk9#50]
OpenJ9 requires mingw to compile bytecode interpreter on windows platforms. Replace it with the default compiler.

**Comment by aprenaud** [comment]
mingw was chosen because the default compiler wouldn't complete compilation with optimizations. chaging back to the default compiler would have major throughput implications.  

Why do we want to do this?

**Comment by pshipton** [comment]
This is a temporary step to get a Windows build working sooner. The mingw version we are using internally seems to be an interim version which isn't available publicly. After the Windows build is running we can circle back and work on getting mingw working again.
