### ISSUE TITLE
OpenJ9 build creates unsupported executables

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk9#52]
The OpenJ9 build creates a number of unsupported executables. These work on Hotspot, but not OpenJ9. While eventually all or some of these executables might be supported, removing them from the build in the meantime avoids confusion caused by trying to use the executables and finding they don't work.

jcmd, jinfo, jmap, jps, jstack, jstat, jstatd

**Comment by Bluevisitor** [comment]
The executables for all of those (except jstatd) are generated by the file "Launcher-jdk.jcmd.gmk".

jstatd is generated by the Launcher-jdk.jstatd.gmk file in the same directory (jdk/make/launcher).

Preventing the creation of these executables should be as simple as removing those lines in the extensions repository.

I recommend leaving the files so we can re-add those features one-by-one as OpenJ9 is made compatible with them (or visa versa).

**Comment by Bluevisitor** [comment]
Peter advised that extension is better than modification.

Unfortunately, simply extending these files won't prevent the creation of the unsupported executables. If the code in these files runs at all, regardless of our extension code, these executables will be generated. 

If we want to prevent these executables being generated, we need to prevent this code being executed. If you know a way to do this via extensions code, please tell me. Else, the only way I see us preventing these executables is deleting the code in those files.

**Comment by pshipton** [comment]
Ideally we should overwrite or overlay the original Launcher-jdk.jcmd.gmk with an empty file, rather than modifying the existing file. The former continues to work if Launcher-jdk.jcmd.gmk is modified, while the latter becomes a merge conflict any time Launcher-jdk.jcmd.gmk is modified.

@andrew-m-leonard

**Comment by Bluevisitor** [comment]
Andrew spotted that we have removed gmk files in this directory, rather than replacing them with empty files, so I will do the same for consistency.

**Comment by pshipton** [comment]
This isn't ideal for maintenance as removing a file becomes a merge conflict any time OpenJDK modifies the original file. Removing the file is essentially deleting every line, which conflicts with changes or additions to the file.

**Comment by Bluevisitor** [comment]
If that's the case, then we should also change this for other deleted files (like jdk/make/lib/Lib-java.management.gmk).

Perhaps a separate issue?

**Comment by Bluevisitor** [comment]
We discussed the issue locally and agreed that we should go for consistency. If there are merge conflict concerns, then I advise raising a separate issue to cover that, and we can then address all of the deleted files (including these) at the same time.

I've created a pull request to cover the change: https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/54

**Comment by Bluevisitor** [comment]
Pull request has been reviewed and accepted.

@pshipton - If the deletion of files will lead to merge conflicts, I encourage you to raise a new issue for it.
