### ISSUE TITLE
Update Jenkins CI to perform auto-check for "Signed-off by: <user>"

### ISSUE THREAD

**Issue by andrew-m-leonard** [ibmruntimes/openj9-openjdk-jdk9#58]

**Comment by DanHeidinga** [comment]
fyi @AdamBrousseau

**Comment by DanHeidinga** [comment]
We'll need to enable this for all the extensions repos - 8, 9, "jdk", and 10, etc as they become available

**Comment by AdamBrousseau** [comment]
@MichelleXiaoxiaoWang has authored a signed-off by check and we are currently testing it on the OpenJ9 PRs before we merge it.
https://ci.eclipse.org/openj9/job/PullRequest-SignedOffByCheck-OpenJDK10

We have been checking 
- The last line of each commit has a 'signed-off-by'
- The second last line is blank. 

I noticed a few commits merged that did not have the second last line blank. They still passed the Eclipse ip-validation check. Should we only be checking the last line @DanHeidinga ?
eg.
- https://github.com/eclipse/openj9/pull/1792/commits
- https://github.com/eclipse/openj9/pull/1952/commits

I also see that this commit didn't have a signed-off-by but still passed the Eclipse check
- https://github.com/eclipse/openj9/pull/1901/commits

Now I'm wondering if they are only checking the commit authors against the ECA

**Comment by AdamBrousseau** [comment]
If Eclipse is only checking the authors, maybe we should have this check at OpenJ9 too.

**Comment by AdamBrousseau** [comment]
Talked to Dan, seems my requirements may have been incorrect on this.
I assumed:
- Last line signed-off-by
- Second last line blank

(based on how `git commit -s` works)

Our [CONTRIBUTING.md](https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md#commit-guidelines) at OpenJ9 says
>- Sign off on your commit in the footer
>- automatically added to your commit by passing `-s` to `git commit`
>- manually adding the following line to the footer
>```Signed-off-by: Full Name <email>```
>- if a blank line is found anywhere after the Signed-off-by line, the Signed-off-by: will be considered outside of the footer, and will fail the automated Signed-off-by validation

The [example commmit](https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md#example-commits) shows the sign-off in the last line but also the issue# in the footer.

More doc at eclipse
https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Signing_off_on_a_commit
Example commit
```
commit 862e6ff22ad56c10df6de3385ffa4c7d02363d1d
Author: Joe Somebody <somebody@someplace.net>
Date:   Mon Jun 17 17:19:38 2013 -0700

    [410937] Auto share multiple projects in single job
    
    When multiple projects are imported together, perform all the necessary
    auto shares in a single job rather than spawning a separate job for each
    project.
    
    Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=410937
    Also-by: Some Otherperson <otherperson@someplace.net>
    Signed-off-by: Joe Somebody <somebody@someplace.net>
```
>Minimally, your Git commit record must have the following:
>- Your credentials (email address) captured in the "Author" field;
>- A single line summary in the message field, followed by a more detailed descriptive paragraph; and
>- A "Signed-off-by" entry with matching credentials in the message footer.
>
>Note that the footer entries must occur at the bottom of the commit message and must not include any blank lines.

I guess we should open a few test PRs to see exactly how the Eclipse check works.

**Comment by AdamBrousseau** [comment]
Can we agree that the check should be "sign off in any line of the footer"? Or do we need to discuss further?
I.e. Find last blank line of commit, one of the lines following must have a sign-off.

**Comment by pshipton** [comment]
Sounds correct.

**Comment by AdamBrousseau** [comment]
This is now implemented and running against 8,9,10,next
