### ISSUE TITLE
configure should detect missing packages

### ISSUE THREAD

**Issue by pdbain-ibm** [ibmruntimes/openj9-openjdk-jdk9#6]
configure detects some missing packages such as zip, but not others such as libnuma-dev.
This causes the build to fail during compilation.

**Comment by jdekonin** [comment]
numa, as well as m4 and bison are required for compiling openj9.

**Comment by rwy0717** [comment]
+1, configure should locate these packages or error out. Where are our build requirements documented?

**Comment by mleipe** [comment]
Build requirements are documented on the [Eclipse OpenJ9 build page](https://www.eclipse.org/openj9/oj9_build.html) in the for of Dockerfiles that can either be used to build Docker images that will build Eclipse OpenJ9 or as "recipes" for building a non-containerized environment.

**Comment by davew16** [comment]
assigning this issue to @jdekonin for answer to @mstoodle's question in the pull request

**Comment by jonathanwoodford** [comment]
Another dependency is freemarker.  This is specified on the configure step:
    bash ./configure --with-freemarker-jar=~/freemarker.jar

If this has not been installed, or the wrong location is specified, this fails at the build phase, not the configure phase.

**Comment by mleipe** [comment]
My experience has been that configure explicitly complains if freemarker is not there, and that it even tells you how to wget and untar it.  I'll check again today.

**Comment by mleipe** [comment]
Okay, I've confirmed your user scenario, @jonathanwoodford, thanks for clarifying earlier today.

If you omit the '--with-freemarker-jar' command-line option, configure complains.

If you include the option and the jar file is not there, or if, as you've tried, you provide a path that does not contain the freemarker jar file, configure doesn't complain.

We need to fix this.  If there's no freemarker.jar, configure should fail.

**Comment by jdekonin** [comment]
Opened #24 to address the freemarker.jar issue raise in the last comment.
