### ISSUE TITLE
Improve how OpenJ9.mk builds the images 

### ISSUE THREAD

**Issue by yongja79** [ibmruntimes/openj9-openjdk-jdk9#67]
The issue to get jlink to work #21 brought up how OpenJ9.gmk builds the build jdk, image jdk and image jre and how it should be improved. 

Is closed/OpenJ9.gmk is the correct place for this. The [pre/post] Images.gmk might be a better location or extending 'module'-libs targets or maybe customizing/extending jdk/make/lib/Lib-java.base.gmk?

If closed/OpenJ9.gmk is the right place, improve the macro used to copy across the J9 files into the images. See if a single macro is possible and if removing the explicit copies can be done. See PR #66 for more information.

**Comment by JamesKingdon** [comment]
We also need to consider how the build jdk should be handled for cross compiling, as that currently doesn't seem to work.

**Comment by andrew-m-leonard** [comment]
this is now obsolete, as the make file has been reworked quite a bit since then now
