### ISSUE TITLE
Create a jextract executable

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk9#68]
Create a jextract executable to call com.ibm.dtfj/com.ibm.jvm.j9.dump.extract.Main

FYI #22

@paulcheeseman

**Comment by pshipton** [comment]
libj9jextract.so will also need to be added into the java.base module, for now.

**Comment by JasonFengJ9** [comment]
module `com.ibm.dtfj` will be renamed to `com.ibm.dtfj` so the executable should call `openj9.dtfj/com.ibm.jvm.j9.dump.extract.Main` instead. For easy transition, could the executable fall back to `com.ibm.dtfj/com.ibm.jvm.j9.dump.extract.Main` if the invocation to `openj9.dtfj` failed?

**Comment by pshipton** [comment]
We don't need to create any fall back, we can just change the main class in the executable at the same time as the module name is changed. @JasonFengJ9 what is the issue/PR for the module change?

**Comment by JasonFengJ9** [comment]
There is no issue created for renaming module `com.ibm.dtfj`. It was an internal `PR 124407`.

**Comment by pshipton** [comment]
Until the change to openj9.dtfj, the jextract executable can use com.ibm.dtfj, and then be changed at the same time as the module is renamed.

**Comment by groeges** [comment]
Adding a new file `jdk/make/launcher/Launcher-com.ibm.dtfj.gmk` with the following content:
```
# ===========================================================================
# (c) Copyright IBM Corp. 2017 All Rights Reserved
# ===========================================================================
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, see <http://www.gnu.org/licenses/>.
#
# ===========================================================================

include LauncherCommon.gmk

$(eval $(call SetupBuildLauncher, jextract, \
    MAIN_MODULE := com.ibm.dtfj, \
    MAIN_CLASS := com.ibm.jvm.j9.dump.extract.Main, \
    CFLAGS := -DEXPAND_CLASSPATH_WILDCARDS, \
))
```
allows the extract executable to be built.
Will raise a pull request to add this to the extensions repository.

**Comment by groeges** [comment]
@andrew-m-leonard If we add this file, which repository should it get added to:
- [ ] openj9-openjdk-jdk8
- [ ] openj9-openjdk-jdk9
- [ ] IBMSDK-java
or does it need to get added to all of them?

**Comment by andrew-m-leonard** [comment]
all of them please Steve

**Comment by groeges** [comment]
@pshipton Does this also need adding to openJ9 with OpenJDK8?

**Comment by pshipton** [comment]
> Does this also need adding to openJ9 with OpenJDK8?

Yes. It is part of the service story for Linux and AIX, used to gather required files for further analysis. https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.lnx.80.doc/diag/tools/dump_viewer_dtfjview/jextract.html

**Comment by groeges** [comment]
OK, looks like it needs adding to all extensions repositories. Will ensure it is added.

**Comment by groeges** [comment]
OpenJ9 with JDK9 extension Pull Request is: https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/97

**Comment by groeges** [comment]
This has been done but until https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/9 is resolved the executables on OpenJ9 with JDK8 will not work correctly. Closing this issue as the executables have been created.

**Comment by pshipton** [comment]
I think you meant ibmruntimes/openj9-openjdk-jdk8#8

**Comment by groeges** [comment]
Yes, I did. I have modified the comment to use the correct link.
