### ISSUE TITLE
AIX build does not generate a jre image

### ISSUE THREAD

**Issue by groeges** [ibmruntimes/openj9-openjdk-jdk9#72]
Building OpenJDK9 with OpenJ9  and also plain OpenJDK9 do not create a JRE image. 

This seems to be a base OpenJDK problem and bug has been raised https://bugs.openjdk.java.net/browse/JDK-8189618

**Comment by groeges** [comment]
The above issue has been resolved and a change made to jdk10: http://hg.openjdk.java.net/jdk10/master/rev/7a7bc84f4b6c

**Comment by groeges** [comment]
@andrew-m-leonard As this has been fixed in OpenJDK10 and not earlier releases, do we want to make the same change in our extensions for OpenJDK9 (and possibly for OpenJDK8). I know we are trying to reduce the extensions, but I thought I would ask before making a change.

**Comment by andrew-m-leonard** [comment]
Yes, JDK8 I think (JDK9 not so important as not LTS). Removing extensions is a JDK10+ plan.

**Comment by groeges** [comment]
This was not needed on JDK8 as it already built a JRE, the Pull Request for this issue is: https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/92 which has been merged.

Closing this issue.
