### ISSUE TITLE
custom-hook.m4 OPENJ9_PLATFORM_SETUP needs to support arm

### ISSUE THREAD

**Issue by JamesKingdon** [ibmruntimes/openj9-openjdk-jdk9#82]
In custom-hook.m4 OPENJ9_PLATFORM_SETUP the if statement on OPENJ9_CPU needs extending to cover arm. The following might be a starting point:
```
  elif test "x$OPENJ9_CPU" = xarm; then
    OPENJ9_PLATFORM_CODE=xr32
    OPENJ9_BUILDSPEC=linux_arm
```

**Comment by DanHeidinga** [comment]
@JamesKingdon Can you open a PR for this change?  

Checkout where `osx` is used in the makefiles / configure files in openjdk as the same places will need to be modified for arm.  I think there were 3 places that needed to be touched for OSX.

**Comment by JamesKingdon** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/87
