### ISSUE TITLE
Main.gmk attempts to compose the buildjvm when it shouldn't

### ISSUE THREAD

**Issue by JamesKingdon** [ibmruntimes/openj9-openjdk-jdk9#83]
Main.gmk will attempt to copy libraries into the build jvm even when using --with-build-jdk. Since the build jvm wasn't built in this case, it's likely that the libraries it was attempting to copy were for the target architecture (cross compiling), and therefore not a good thing to do.
Commenting out the j9vm-compose-buildjvm target helped in the short term, but I tihnk this needs to be made conditional in some way.

**Comment by JamesKingdon** [comment]
This issue is addressed for arm cross compiles by PR #87 and #88 but those changes should probably be generalised to handle --with-build-jdk on native builds.

**Comment by keithc-ca** [comment]
I believe this was fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/155.
I tested using
```
configure --with-build-jdk={read-only-bootjdk9} ...
```
without incident.
