### ISSUE TITLE
Enable static build on Linux

### ISSUE THREAD

**Issue by cosmin-ionita** [ibmruntimes/openj9-openjdk-jdk9#89]
Hello!

I saw that static building is only allowed on macosx systems (by using --enable-static-build flag). Why can't it be allowed on Linux systems? What are the differences between static building on macosx and Linux?

I tried to do that on the latest version on Open J9 and I reached the following line:

$(NM) -m $$($1_TARGET) | $(GREP)  "__TEXT" | \
        $(EGREP) -v "non-external|private extern|__TEXT,__eh_frame" | \
        $(SED) -e  's/.* //' > $$(@D)/$$(basename $$(@F)).symbols; \

This line is located in the function GetSymbols, in the file $(ROOT)/make/common/NativeCompilation.gmk.

After some research I found out that $(NM) command (in Linux) doesn't have the -m option. On macosx, the $(NM) command does have that option.

Is there a way to replace that $(NM) -m (available only on macosx) with a Linux equivalent command?

Thanks in advance.

**Comment by andrew-m-leonard** [comment]
If this is still a requirement, it's probably worth discussing on in the openjdk community with regards static linking options
